#!/bin/bash
# Version 1.4
# Snapshot website ( code and database )
#
#		Author	: Viki (a) Vignesh Natarajan 
#		Contact	: vikiworks.io
#		Licence : MIT

ARG0=$0
ARG1=$1

function get_current_dir()
{
    CURRENT_DIR=`pwd -P`
}

function command_exec_dir_check()
{
	if [ ! -f snapshot ]; then
		echo "error: command should be executed from backupNrestore directory"
		exit 1
	fi
}

function import_config()
{
    cd $CURRENT_DIR
    source ./config.sh
    [ $? -ne 0 ] && { echo "[ $TIME_STAMP ] [ ERROR ] [ ${LINENO} ] "; exit 1; }
    echo
    echo
}

function is_git_config_valid()
{
    config_error=0

    echo

    [ -z "$GIT_USERNAME" ] && { echo "  [ CONFIG ERROR ] :  GIT_USERNAME" ; config_error=1; }
    [ -z "$GIT_EMAIL" ] && { echo "  [ CONFIG ERROR ] :  GIT_EMAIL" ; config_error=1; }

    if [ $config_error -eq 1 ]; then
        echo
        echo "  [ ERROR ] Fix configuration error and try again ( config.sh ) "
        echo
        exit 1
   fi
}


function get_timestamp()
{
    DAY=$(date '+%d')
    MONTH=$(date '+%m')
    YEAR=$(date '+%Y')
    HOUR=$(date '+%H')
    MINUTE=$(date '+%M')
    TIME_STAMP="D${DAY}${MONTH}${YEAR}#T${HOUR}${MINUTE}"
}

function switch2master_branch_if_exist()
{
    git branch | grep master 2> /dev/null 1> /dev/null
    
    if [ $? -eq 0 ]; then 
        git checkout master 2> /dev/null 1> /dev/null
    fi 
}

function git_checkout()
{
    BRANCH_NAME="master"
    git branch | grep $BRANCH_NAME 2> /dev/null 1> /dev/null
    if [ $? -eq 0 ]; then 
        BRANCH_NAME="${TIME_STAMP}"
        echo "  Creating branch ( $BRANCH_NAME )"
        git checkout -b "$BRANCH_NAME"
    fi
    switch2master_branch_if_exist
}

function remove_git_from_backupNrestore_dir()
{
    cd $CURRENT_DIR
    rm -rf .git
}

function git_commit()
{
    cd ../
    git init
    git config --local user.email   "$GIT_EMAIL"
    git config --local user.name    "$GIT_USERNAME"
  
    switch2master_branch_if_exist

    git add .
    git commit -m "$TIME_STAMP"
    
    git_checkout 

    echo "  DB is backed up and source code is versioned locally with git"
    echo 
    echo "  Complete source and db - base location : ( `pwd` )"
    echo ""
    echo "  Branch Name : $BRANCH_NAME"
    echo ""
    echo "  A snapshot of the website is done"
    echo ""

    cd $CURRENT_DIR
}

function is_git_installed()
{
    which git 2>/dev/null 1>/dev/null
    if [ $? -ne 0 ]; then 
        echo "  warning: git is not installed, unable to snapshot"
        echo ""
        echo "  Install git before trying snapshot"
        echo ""
        exit 1
    fi
}

function backup_db(){
    echo "  exporting database(s)"
    ./db_backup
}

function git_snapshot()
{
    is_git_installed
    get_current_dir
    command_exec_dir_check

    if [ $ARG1 == "no_db_export"]; then
        echo "  [ status ] snapshot without db export"
    else
        echo "  [ status ] snapshot with db export"
        backup_db
    fi
    
    import_config
    is_git_config_valid
    get_timestamp
    remove_git_from_backupNrestore_dir
    git_commit
}

if [ -z $ARG1 ]; then
    ARG1="export_db"
fi

git_snapshot 
exit 0
