#!/bin/bash

# restore a website from from backup
#
#		Author	: Viki (a) Vignesh Natarajan 
#		Contact	: vikiworks.io
#		Licence : MIT

TOOL_NAME="backupNrestore"
config_mismatch=0

function get_current_dir()
{
    CURRENT_DIR=`pwd -P`
}

function create_db_if_not_exist(){
    DB_NAME=$1
    echo "Creating DB if not exist ( $DB_NAME )"

    if [[ -z $MYSQL_ADMIN_USERNAME ]]; then
        echo "[ error ] You don't have permission to create DB, Manually create DB using phpMyAdmin and try again"
        exit 1
    fi

    mysql -u$MYSQL_ADMIN_USERNAME -p$MYSQL_ADMIN_PASSWORD -h $DB_HOST -P $DB_PORT -e "CREATE DATABASE IF NOT EXISTS $DB_NAME;" 2>/dev/null 1>/dev/null 
}

function create_db_user_if_not_exist(){
    DB_NAME=$1
    DB_USER=$2
    DB_PASS=$3

    echo "Creating DB USER if not exist ( $DB_USER )"

    if [[ -z $MYSQL_ADMIN_USERNAME ]]; then
        echo "[ error ] You don't have permission to create DB, Manually create DB using phpMyAdmin and try again"
        exit 1
    fi

    mysql -u$MYSQL_ADMIN_USERNAME -p$MYSQL_ADMIN_PASSWORD -h $DB_HOST -P $DB_PORT -e "CREATE USER '$DB_USER'@'$DB_HOST' IDENTIFIED BY '$DB_PASS';" 2>/dev/null 1>/dev/null

    echo "update db password"
    mysql -u$MYSQL_ADMIN_USERNAME -p$MYSQL_ADMIN_PASSWORD -h $DB_HOST -P $DB_PORT -e "SET PASSWORD FOR '$DB_USER'@'$DB_HOST' = PASSWORD('$DB_PASS');" 2>/dev/null 1>/dev/null
    
    echo "grand db privileges"
    #mysql -u$MYSQL_ADMIN_USERNAME -p$MYSQL_ADMIN_PASSWORD -h $DB_HOST -P $DB_PORT -e "GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO '$DB_USER'@'$DB_HOST';" 2>/dev/null 1>/dev/null
    mysql -u$MYSQL_ADMIN_USERNAME -p$MYSQL_ADMIN_PASSWORD -h $DB_HOST -P $DB_PORT -e "GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO '$DB_USER'@'$DB_HOST' WITH GRANT OPTION;" 2>/dev/null 1>/dev/null
    #mysql -u$MYSQL_ADMIN_USERNAME -p$MYSQL_ADMIN_PASSWORD -h $DB_HOST -P $DB_PORT $DB_NAME -e "GRANT ALL PRIVILEGES TO '$DB_USER'@'$DB_HOST';" 2>/dev/null 1>/dev/null
    #mysql -u$MYSQL_ADMIN_USERNAME -p$MYSQL_ADMIN_PASSWORD -h $DB_HOST -P $DB_PORT -e "GRANT ALL PRIVILEGES ON *.* TO '$DB_USER'@'$DB_HOST';" 2>/dev/null 1>/dev/null
    #mysql -u$MYSQL_ADMIN_USERNAME -p$MYSQL_ADMIN_PASSWORD -h $DB_HOST -P $DB_PORT -e "GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, INDEX, DROP, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES ON ${DB_NAME}.* TO '$DB_USER'@'$DB_HOST';" 2>/dev/null 1>/dev/null
}

function is_db_empty()
{
    DB_NAME=$1
    DB_USER=$2
    DB_PASS=$3
    CMD_STATUS=1

    if [[ -z $MYSQL_ADMIN_USERNAME ]]; then
        table_count=$(mysql -u$DB_USER -p$DB_PASS -h $DB_HOST -P $DB_PORT $DB_NAME -e "SHOW TABLES;" 2> /dev/null | wc -l)
        mysql -u$DB_USER -p$DB_PASS -h $DB_HOST -P $DB_PORT $DB_NAME -e "SHOW TABLES;" 1> /dev/null 2> /dev/null
        CMD_STATUS=$?
    else
        table_count=$(mysql -u$MYSQL_ADMIN_USERNAME -p$MYSQL_ADMIN_PASSWORD -h $DB_HOST -P $DB_PORT $DB_NAME -e "SHOW TABLES;" 2> /dev/null | wc -l)
        mysql -u$MYSQL_ADMIN_USERNAME -p$MYSQL_ADMIN_PASSWORD -h $DB_HOST -P $DB_PORT $DB_NAME -e "SHOW TABLES;" 1> /dev/null 2> /dev/null
        CMD_STATUS=$?
    fi

    if [ $CMD_STATUS -ne 0 ]; then
        echo "info1: probably db ($DB_NAME) doesn't exist"
        echo "info2: probably db_user ($DB_USER) doesn't exist"
        echo "info3: probably db_password ($DB_PASS) is wrong"
        create_db_if_not_exist $DB_NAME
        create_db_user_if_not_exist $DB_NAME $DB_USER $DB_PASS
    else
        if [ $table_count -gt 0 ];then
            echo "  [ ERROR ] [ ${LINENO} ] DB is not empty ( $DB_NAME ) ( table_count : $table_count ), truncate database before restore"
            echo
            echo "  Help: Truncate Database"
            echo
            echo "  ./truncate_db '$DB_HOST' '$DB_PORT' '$DB_NAME' '$DB_USER' '$DB_PASS'"
            echo
            exit 1
        fi
    fi

}

function db_empty_check()
{
	if [ ! -z $DB1_NAME ]; then
	    is_db_empty  $DB1_NAME $DB1_USERNAME  $DB1_PASSWORD 
	fi

	if [ ! -z $DB2_NAME ]; then
	    is_db_empty  $DB2_NAME $DB2_USERNAME  $DB2_PASSWORD 
	fi

	if [ ! -z $DB3_NAME ]; then
	    is_db_empty  $DB3_NAME $DB3_USERNAME  $DB3_PASSWORD 
	fi

	if [ ! -z $DB4_NAME ]; then
	    is_db_empty  $DB4_NAME $DB4_USERNAME  $DB4_PASSWORD 
	fi
}

function create_website_root_if_not_exist(){
    mkdir -p ${WEBSITE_ROOT_DIR} 2> /dev/null 1> /dev/null
}

function dir_empty_check()
{

    file_count=`ls ${WEBSITE_ROOT_DIR}/ | wc -l`
    if [ $file_count -gt 0 ];then
        echo "  [ ERROR ] [ ${LINENO} ] website root directory ( $WEBSITE_ROOT_DIR ) is not empty, clear all files before restoring"
        echo
        echo "  Help: Clear all files from website root"
        echo
        echo "  rm -rf $WEBSITE_ROOT_DIR/*"
        echo

        exit 1
    fi
}

function config_mismatch_check(){
    OLD=$1
    NEW=$2
    if [ "$OLD" != "$NEW" ]; then
	echo "  [ WARNING ] manually search and replace the following string,"
        echo
	echo "    [ $OLD -> $NEW ]"
        echo
        echo "    Location to change: "
        echo "    "
        echo "        -> $SOURCE_PATH/db"
        echo "        -> $SOURCE_PATH/code"
        echo "        -> $CURRENT_DIR/.config_old.sh"
        echo "    "
	config_mismatch=1
    fi
}

function verify_config()
{
    config_mismatch_check $OLD_DOMAIN $DOMAIN

    config_mismatch_check $OLD_WEBSITE_ROOT_DIR $WEBSITE_ROOT_DIR

    config_mismatch_check $OLD_DB1_NAME $DB1_NAME
    config_mismatch_check $OLD_DB2_NAME $DB2_NAME
    config_mismatch_check $OLD_DB3_NAME $DB3_NAME
    config_mismatch_check $OLD_DB4_NAME $DB4_NAME

    config_mismatch_check $OLD_DB1_USERNAME $DB1_USERNAME
    config_mismatch_check $OLD_DB2_USERNAME $DB2_USERNAME
    config_mismatch_check $OLD_DB3_USERNAME $DB3_USERNAME
    config_mismatch_check $OLD_DB4_USERNAME $DB4_USERNAME

    config_mismatch_check $OLD_DB1_PASSWORD $DB1_PASSWORD 
    config_mismatch_check $OLD_DB2_PASSWORD $DB2_PASSWORD
    config_mismatch_check $OLD_DB3_PASSWORD $DB3_PASSWORD
    config_mismatch_check $OLD_DB4_PASSWORD $DB4_PASSWORD
}


function import_config()
{
    #Old Config
    if [ ! -f "$CURRENT_DIR/.config_old.sh" ]; then
        echo "  [ ERROR ] Restore Failed, Old config file missing ( $CURRENT_DIR/.config_old.sh )"
        exit 1
    fi

    source $CURRENT_DIR/.config_old.sh
    OLD_DOMAIN=$DOMAIN 
    OLD_WEBSITE_ROOT_DIR=$WEBSITE_ROOT_DIR
    OLD_DB1_NAME=$DB1_NAME 
    OLD_DB2_NAME=$DB2_NAME 
    OLD_DB3_NAME=$DB3_NAME 
    OLD_DB4_NAME=$DB4_NAME 
 
    OLD_DB1_USERNAME=$DB1_USERNAME 
    OLD_DB2_USERNAME=$DB2_USERNAME 
    OLD_DB3_USERNAME=$DB3_USERNAME 
    OLD_DB4_USERNAME=$DB4_USERNAME 

    OLD_DB1_PASSWORD=$DB1_PASSWORD  
    OLD_DB2_PASSWORD=$DB2_PASSWORD  
    OLD_DB3_PASSWORD=$DB3_PASSWORD  
    OLD_DB4_PASSWORD=$DB4_PASSWORD  
 

    #New Config
    if [ -f "$CURRENT_DIR/config.sh" ]; then
        echo "  [ status ] importing config ( $CURRENT_DIR/config.sh )"
        source $CURRENT_DIR/config.sh
    else
        echo "  [ ERROR ] Restore Failed, config file missing ( $CURRENT_DIR/config.sh )"
        exit 1
    fi

    verify_config

    if [ $config_mismatch -eq 1 ]; then
        echo " [ ERROR ] there is a mismatch in old and new configuration, fix the configuration and try restore again"
        exit 1
    fi
}

#Get Website Source Path
function set_source_path()
{
    cd $CURRENT_DIR
    [ $? -ne 0 ] && { echo "  [ ERROR ] [ ${LINENO} ]"; exit 1; }
    cd ..
    SOURCE_PATH=`pwd -P`
}

function check_whether_webroot_dir_inside_source_dir()
{
    # Example:
    #   
    #   if (/home/backup/website) inside ( /home/backup ) : TRUE 
    #   
    if [[ $WEBSITE_ROOT_DIR =~ "$SOURCE_PATH" ]]; then
        echo
        echo "  [ possible error ] It looks like new website root directory is inside source directory"
        echo
        echo "       -> [ SOURCE_DIR : $SOURCE_PATH ]"
        echo
        echo "       -> [ WEBSITE_ROOT_DIR : $WEBSITE_ROOT_DIR ]"
        echo
        echo
        exit 1
    fi  
} 

function exit_if_space_exist(){
    STR="$1"
    MESSAGE="$2"
    if [[ "$STR" == *" "* ]]; then
        echo "  error: ( $MESSAGE ) - ( "$STR" ) "
        echo
        exit 1
    fi
}

function exit_if_dollar_exist(){
    STR="$1"
    MESSAGE="$2"
    if [[ "$STR" == *"$"* ]]; then
        echo "  error: ( $MESSAGE ) - ( "$STR" ) "
        echo
        exit 1
    fi
}


function empty_config_check()
{
    config_error=0

    echo
    [ -z $DOMAIN ] && { echo "  [ CONFIG ERROR ] :  DOMAIN" ; config_error=1; }
    [ -z $DB1_NAME ] && { echo "  [ CONFIG ERROR ] :  DB1_NAME" ; config_error=1; }
    [ -z $DB1_USERNAME ] && { echo "  [ CONFIG ERROR ] :  DB1_USERNAME" ; config_error=1; }
    [ -z $DB1_PASSWORD ] && { echo "  [ CONFIG ERROR ] :  DB1_PASSWORD" ; config_error=1; }
    [ -z $DB_HOST ] && { echo "  [ CONFIG ERROR ] :  DB_HOST" ; config_error=1; }
    [ -z $DB_PORT ] && { echo "  [ CONFIG ERROR ] :  DB_PORT" ; config_error=1; }
    [ -z $WEBSITE_ROOT_DIR ] && { echo "  [ CONFIG ERROR ] :  WEBSITE_ROOT_DIR" ; config_error=1; }
    [ -z $BACKUP_DIR ] && { echo "  [ CONFIG ERROR ] :  BACKUP_DIR" ; config_error=1; }

    if [ $config_error -eq 1 ]; then
        echo
        echo "  [ ERROR ] Website Restore Failed, Invalid Configuration( $CURRENT_DIR/config.sh ) "
        echo
        exit 1
   fi

   exit_if_space_exist "$CURRENT_DIR"       "Space character is not supported in CURRENT_DIR"
   exit_if_space_exist "$WEBSITE_ROOT_DIR"  "Space character is not supported in WEBSITE_ROOT_DIR"
   exit_if_space_exist "$DOMAIN"            "Space character is not supported in DOMAIN"
   exit_if_space_exist "$DB1_NAME"          "Space character is not supported in DB1_NAME"
   exit_if_space_exist "$DB2_NAME"          "Space character is not supported in DB2_NAME"
   exit_if_space_exist "$DB3_NAME"          "Space character is not supported in DB3_NAME"
   exit_if_space_exist "$DB4_NAME"          "Space character is not supported in DB4_NAME"
   exit_if_space_exist "$DB1_USERNAME"      "Space character is not supported in DB1_USERNAME"
   exit_if_space_exist "$DB2_USERNAME"      "Space character is not supported in DB2_USERNAME"
   exit_if_space_exist "$DB3_USERNAME"      "Space character is not supported in DB3_USERNAME"
   exit_if_space_exist "$DB4_USERNAME"      "Space character is not supported in DB4_USERNAME"
   exit_if_space_exist "$DB1_PASSWORD"      "Space character is not supported in DB1_PASSWORD"
   exit_if_space_exist "$DB2_PASSWORD"      "Space character is not supported in DB2_PASSWORD"
   exit_if_space_exist "$DB3_PASSWORD"      "Space character is not supported in DB3_PASSWORD"
   exit_if_space_exist "$DB4_PASSWORD"      "Space character is not supported in DB4_PASSWORD"
   exit_if_space_exist "$DB_HOST"           "Space character is not supported in DB_HOST"
   exit_if_space_exist "$DB_PORT"           "Space character is not supported in DB_PORT"
   exit_if_space_exist "$BACKUP_DIR"        "Space character is not supported in BACKUP_DIR"
   exit_if_space_exist "$MYSQL_ADMIN_USERNAME"      "Space character is not supported in MYSQL_ADMIN_USERNAME"
   exit_if_space_exist "$MYSQL_ADMIN_PASSWORD"      "Space character is not supported in MYSQL_ADMIN_PASSWORD"

   exit_if_dollar_exist "$CURRENT_DIR"       "Space character is not supported in CURRENT_DIR"
   exit_if_dollar_exist "$WEBSITE_ROOT_DIR"  "Dollar character is not supported in WEBSITE_ROOT_DIR"
   exit_if_dollar_exist "$DOMAIN"            "Dollar character is not supported in DOMAIN"
   exit_if_dollar_exist "$DB1_NAME"          "Dollar character is not supported in DB1_NAME"
   exit_if_dollar_exist "$DB2_NAME"          "Dollar character is not supported in DB2_NAME"
   exit_if_dollar_exist "$DB3_NAME"          "Dollar character is not supported in DB3_NAME"
   exit_if_dollar_exist "$DB4_NAME"          "Dollar character is not supported in DB4_NAME"
   exit_if_dollar_exist "$DB1_USERNAME"      "Dollar character is not supported in DB1_USERNAME"
   exit_if_dollar_exist "$DB2_USERNAME"      "Dollar character is not supported in DB2_USERNAME"
   exit_if_dollar_exist "$DB3_USERNAME"      "Dollar character is not supported in DB3_USERNAME"
   exit_if_dollar_exist "$DB4_USERNAME"      "Dollar character is not supported in DB4_USERNAME"
   exit_if_dollar_exist "$DB1_PASSWORD"      "Dollar character is not supported in DB1_PASSWORD"
   exit_if_dollar_exist "$DB2_PASSWORD"      "Dollar character is not supported in DB2_PASSWORD"
   exit_if_dollar_exist "$DB3_PASSWORD"      "Dollar character is not supported in DB3_PASSWORD"
   exit_if_dollar_exist "$DB4_PASSWORD"      "Dollar character is not supported in DB4_PASSWORD"
   exit_if_dollar_exist "$DB_HOST"           "Dollar character is not supported in DB_HOST"
   exit_if_dollar_exist "$DB_PORT"           "Dollar character is not supported in DB_PORT"
   exit_if_dollar_exist "$BACKUP_DIR"        "Dollar character is not supported in BACKUP_DIR"
   exit_if_dollar_exist "$MYSQL_ADMIN_USERNAME"      "Dollar character is not supported in MYSQL_ADMIN_USERNAME"
   exit_if_dollar_exist "$MYSQL_ADMIN_PASSWORD"      "Dollar character is not supported in MYSQL_ADMIN_PASSWORD"
}

function remove_trailing_slash()
{
   BACKUP_DIR=`echo ${BACKUP_DIR%/}`
   BACKUP_DIR=`echo ${BACKUP_DIR%/}`
   
   WEBSITE_ROOT_DIR=`echo ${WEBSITE_ROOT_DIR%/}`
   WEBSITE_ROOT_DIR=`echo ${WEBSITE_ROOT_DIR%/}`
   
   DOMAIN=`echo ${DOMAIN%/}`
   DOMAIN=`echo ${DOMAIN%/}`
}

function print_config()
{
    echo
    echo "  Website Root      : $WEBSITE_ROOT_DIR"
    echo "  Backup Directory  : $BACKUP_DIR"
    echo "  DB HOST           : $DB_HOST"
    echo "  DB PORT           : $DB_PORT"
    
    [ ! -z $DB1_NAME ] && 	{ echo "  DB NAME          (1) : $DB1_NAME"; }
    [ ! -z $DB2_NAME ] && 	{ echo "  DB NAME          (2) : $DB2_NAME"; }
    [ ! -z $DB3_NAME ] && 	{ echo "  DB NAME          (3) : $DB3_NAME"; }
    [ ! -z $DB4_NAME ] && 	{ echo "  DB NAME          (4) : $DB4_NAME"; }
    echo 
    echo 
    echo 
    [ ! -z $DB1_USERNAME ] && 	{ echo "  DB USERNAME      (1) : $DB1_USERNAME"; }
    [ ! -z $DB2_USERNAME ] && 	{ echo "  DB USERNAME      (2) : $DB2_USERNAME"; }
    [ ! -z $DB3_USERNAME ] && 	{ echo "  DB USERNAME      (3) : $DB3_USERNAME"; }
    [ ! -z $DB4_USERNAME ] && 	{ echo "  DB USERNAME      (4) : $DB4_USERNAME"; }
     
    #echo "  Backup Label      : $BACKUP_LABEL"
    #echo "  Backup File       : ${BACKUP_LABEL}.tar.gz"
    echo 
}


function get_abs_path_website_root()
{
    cd $WEBSITE_ROOT_DIR
    [ $? -ne 0 ] && { echo "  [ ERROR ] [ ${LINENO} ]"; exit 1; }
    WEBSITE_ROOT_DIR=`pwd -P`
}

function import_db(){
	DB_NAME=$1
	DB_USER=$2
	DB_PASS=$3
	DB_DUMP=$4
    cd $SOURCE_PATH

    ls $DB_DUMP 2>/dev/null 1>/dev/null

    if [ $? -ne 0 ]; then
        echo "    error: DB dump file missing ($SOURCE_PATH/$DB_DUMP )"
        exit 1
    fi


	if [[ -z $MYSQL_ADMIN_USERNAME ]]; then
		mysql -u$DB_USER  -p$DB_PASS -h $DB_HOST  -P $DB_PORT $DB_NAME < $DB_DUMP 2>/dev/null 1>/dev/null
		[ $? -ne 0 ] && { echo "  [ ERROR ] [ ${LINENO} ] Database Import Failed ( DB_NAME : $DB_NAME) "; exit 1; }
	else
		mysql -u$MYSQL_ADMIN_USERNAME  -p$MYSQL_ADMIN_PASSWORD -h $DB_HOST -P $DB_PORT $DB_NAME < $DB_DUMP 2>/dev/null 1>/dev/null
		[ $? -ne 0 ] && { echo "  [ ERROR ] [ ${LINENO} ] Database Import Failed ( DB_NAME : $DB_NAME) "; exit 1; }
	fi


}

function importe_database()
{
    cd $SOURCE_PATH

    if [ ! -z $DB1_NAME ]; then
    import_db $DB1_NAME $DB1_USERNAME $DB1_PASSWORD "db/${DB1_NAME}.sql"
    fi

    if [ ! -z $DB2_NAME ]; then
    import_db $DB2_NAME $DB2_USERNAME $DB2_PASSWORD "db/${DB2_NAME}.sql"
    fi
    
    if [ ! -z $DB3_NAME ]; then
    import_db $DB3_NAME $DB3_USERNAME $DB3_PASSWORD "db/${DB3_NAME}.sql"
    fi    
    
    if [ ! -z $DB4_NAME ]; then
    import_db $DB4_NAME $DB4_USERNAME $DB4_PASSWORD "db/${DB4_NAME}.sql"
    fi
}

function importe_code()
{
    cd $SOURCE_PATH

    cp -arf code/. ${WEBSITE_ROOT_DIR}/ 2>/dev/null 1>/dev/null
    if [ $? -ne 0 ]; then
        #some system doesn't support -a option
        cp -rf code/. ${WEBSITE_ROOT_DIR}/
        [ $? -ne 0 ] && { echo "  [ ERROR ] [ ${LINENO} ] Website copy failed"; exit 1; }
        cp -rf code/.htaccess ${WEBSITE_ROOT_DIR}/
        cp -rf code/*.* ${WEBSITE_ROOT_DIR}/
    fi
}

function update_backupNrestore_tool(){
    cd $SOURCE_PATH
    cp -arf $TOOL_NAME ${WEBSITE_ROOT_DIR}/ 2>/dev/null 1>/dev/null
    if [ $? -ne 0 ]; then
        #some system doesn't support -a option
        cp -rf $TOOL_NAME ${WEBSITE_ROOT_DIR}/
        [ $? -ne 0 ] && { echo "  [ ERROR ] [ ${LINENO} ] ( $TOOL_NAME ) copy failed"; exit 1; }
    fi
}

function verify_dns_config()
{
    server_ip=`ping $DOMAIN -c1 | head -1 | grep -Eo '[0-9.]{4,}'`
    ifconfig | grep $server_ip 2>/dev/null 1>/dev/null

    if [ $? -ne 0 ]; then
	echo 
	echo "  [ WARNING! ] Probably domain name ( $DOMAIN ) is not pointing to this server, fix DNS config or nginx configuration"
	echo
	verify_error=1
    fi
}

function verify_restore()
{

    verify_dns_config

    echo
    if [ $verify_error -eq 1 ]; then
       echo "  [ WARNING ] website restore successfully, with minor issues ( Manually fix these issues ) ( $DOMAIN )"
    else
       echo "  [ SUCCESS ] website restore successfully ( $DOMAIN )"
    fi
    echo
}

function configure_ownership(){
    chown www-data:www-data ${WEBSITE_ROOT_DIR} -R 2>/dev/null 1>/dev/null
}

function main()
{
    get_current_dir
    import_config
    set_source_path
    check_whether_webroot_dir_inside_source_dir
    empty_config_check
    remove_trailing_slash
    print_config
    get_abs_path_website_root
    create_website_root_if_not_exist
    dir_empty_check
    db_empty_check
    importe_database
    importe_code
    update_backupNrestore_tool
    configure_ownership
    verify_restore
}

# Call Main Function
main


